IMAGE_NAME = "cs-c4300/pfsense"

Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd
  config.vm.box = IMAGE_NAME
  config.ssh.shell = "sh"
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.network :forwarded_port,
    guest: 443,
    host: 8989,
    host_ip: "127.0.0.1"

  config.vm.network "private_network",
    ip: "192.168.56.10",
    virtualbox__intnet: false

  config.vm.network "private_network",
    auto_config: false,
    virtualbox__intnet: "intnet"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "pfsense-box"
    vb.memory = 1024
    vb.cpus = 2
  end
end